version: '3.1'

services:

  db:
    container_name: mysql
    image: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: school
      MYSQL_USER: demo-user
      MYSQL_PASSWORD: Nbmna.?ha1213
    ports:
      - 3306:3306
    networks:
      - demo-network

  adminer:
    container_name: adminer
    image: adminer
    hostname: sql-admin
    restart: always
    ports:
      - 9080:8080
    depends_on:
      - db
    networks:
      - demo-network

  sonar:
    container_name: sonar
    image: sonarqube
    hostname: sonar
    restart: always
    ports:
      - 9000:9000
    networks:
      - demo-network

  demo:
    container_name: demo-service-1
    image: demo:latest
    hostname: demo
    build:
      context: demo
      dockerfile: Dockerfile
      args:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: school
        MYSQL_USER: demo-user
        MYSQL_PASSWORD: Nbmna.?ha1213
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
