version: '3.1'

services:

  db:
    image: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: school
      MYSQL_USER: demo-user
      MYSQL_PASSWORD: Nbmna.?ha1213
    ports:
      - 3306:3306

  adminer:
    image: adminer
    hostname: sql-admin
    restart: always
    ports:
      - 9080:8080
    depends_on:
      - db
      
  sonar:
    image: sonarqube
    hostname: sonar
    restart: always
    ports:
      - 9000:9000

  demo:
    image: demo
    hostname: demo
    build:
      args:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: school
        MYSQL_USER: demo-user
        MYSQL_PASSWORD: Nbmna.?ha1213
      dockerfile: Dockerfile
      context: ./demo
    ports:
      - 8081:8080
    depends_on:
      - db
